FROM python:3

RUN pip3 install numpy scipy matplotlib ipython jupyter pandas sympy nose astropy peakutils

# WORKDIR /DataProcessingForMaserObservation
#ADD ./code/main.py /
#ARG SOURCE

# CMD [ "python3", "-u", "./main.py", $SOURCE ]

#CMD [ "python3", "-u", "./main.py", "cepa"]


#RUN python3 ./main.py  $sourceName